Save search submit to local storage
Constructor-io/constructorio-ui-autocomplete pull request #139
Opened 2024-05-02 20:21 UTC by mocca102

2024-05-02 20:21 UTC, mocca102 commented on src/beaconUtils.js
> +export const CONSTANTS = {
Copied from the beacon code

2024-05-07 17:53 UTC, esezen requested changes

2024-05-07 17:53 UTC, esezen commented on src/utils.ts
> +import { storageSetItem, storeRecentSearch, storeRecentAction, CONSTANTS } from './beaconUtils';
Lint

2024-05-07 17:53 UTC, esezen commented on src/utils.ts
> +export const addTrackSearchSubmit = (cioClient, term, autocompleteData = {}) => {
Naming thing we talked about

2024-05-07 20:51 UTC, esezen approved these changes
LGTM! Let's get one more review

2024-05-13 14:08 UTC, merged