[NOCI] Fix infinite sections updates
Constructor-io/constructorio-ui-autocomplete pull request #158
Opened 2024-07-24 18:06 UTC by HHHindawy

2024-07-25 21:20 UTC, jjl014 reviewed
This seems to be working great from what I can tell, but let's get another review from the team that's more familiar with the repo.

I was able to reproduce the issue (screenshot attached), but I wasn't sure how you tested the changes. Here are the steps that I took to test your changes:
* Pulled down the PR
* Run `npm run compile`
* Copy the generated `lib` directory and replaced the existing `lib` folder within the test project’s `@constructor-io/constructorio-ui-autocomplete` directory in `node_modules`.

![Screenshot 2024-07-25 at 1 15 58 PM](https://github.com/user-attachments/assets/088ae1d9-f525-49bd-94a4-96cc38d3dc37)

2024-07-29 21:55 UTC, mocca102 requested changes
I believe the issue persists for object parameters other than `sections` like `zeroStateSections`

2024-07-30 21:15 UTC, mocca102 commented
This looks good to me. @esezen @jjl014 Do you see any issue with the used approach?

2024-07-31 12:43 UTC, esezen approved these changes
LGTM!

2024-08-01 17:21 UTC, merged